server:
  addr: 0.0.0.0:8002
  debug: true

redis:
  addr: 192.168.0.101:6379

jwt:
  key: "123456"
  expire:

trace:
  name: access
  endpoint: http://192.168.0.101:14268/api/traces
  sampler:
  enable: false

log:
  level: info
  target:
    - 
      type: console

user_client:
  type: etcd
  etcd:
    key: user.rpc
    addr: 192.168.0.101:2379

message_client:
  type: etcd
  etcd:
    key: message.rpc
    addr: 192.168.0.101:2379

kafka:
  brokers:
  - "192.168.0.101:9192"
  - "192.168.0.101:9292"
  - "192.168.0.101:9392"
  consumer_group:
    - 
      topic: "message"
      group: "access-message"
    - 
      topic: "apply-friend-notify"
      group: "access-friend"
    - 
      topic: "group-apply-notify"
      group: "access-group"