server:
  addr: 127.0.0.1:8004
  debug: true

redis:
  addr: 192.168.0.101:6379

jwt:
  key: "123456"
  expire:

trace:
  name: seqserver
  endpoint: http://192.168.0.101:14268/api/traces
  sampler:
  enable: false

log:
  level: info
  target:
    - 
      type: console