server:
  addr: 127.0.0.1:8003
  debug: true

jwt:
  key: "123456"
  expire:

trace:
  name: gateway
  endpoint: http://192.168.56.133:14268/api/traces
  sampler:
  enable: false

log:
  level: info
  target:
    - 
      type: console

user_client:
  type: etcd
  etcd:
    key: user.rpc
    addr: 192.168.56.133:2379

message_client:
  type: etcd
  etcd:
    key: message.rpc
    addr: 192.168.56.133:2379